name: almaviva_cli
description: A sample command-line application.
version: 1.0.2
repository: https://github.com/rehamahmd/almaviva_cli.git

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ansi: ^0.4.2
  ansicolor: ^2.0.3
  args: ^2.4.2
  cli_spinner: ^1.0.4
  console_menu: ^0.0.1-dev.1
  dart_console: ^4.1.2
  io: ^1.0.5 
  path: ^1.9.1
  process_run: ^1.2.4



dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
 
executables:
  alma: almaviva_cli.dart